version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
